/*
 * This source file was generated by the Gradle 'init' task
 */
package me.dmjohnson.teql;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void createApp() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest);
    }
}
