/*
 * This source file was generated by the Gradle 'init' task
 */
package me.dmjohnson.teql;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class ParserTest {
    TeqlParser setup(String testSyntax){
        CharStream inputStream = CharStreams.fromString(testSyntax);
        TeqlLexer lexer = new TeqlLexer(inputStream);
        CommonTokenStream tokens = new CommonTokenStream(lexer);
        return new TeqlParser(tokens);
    }

    @Test void createApp() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest);
    }
}
